-- Set the database and schema context
USE UNRAVEL_REVERSE_SHARE_DB;
USE UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA;

-- Create or replace the stored procedure for static rightsizing
CREATE OR REPLACE PROCEDURE SP_EXECUTE_STATIC_RIGHTSIZING(db_name VARCHAR, schema_name VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    current_day_of_week VARCHAR DEFAULT TO_CHAR(CURRENT_DATE, 'DY');
    current_hour_of_day VARCHAR DEFAULT LPAD(EXTRACT(HOUR FROM CURRENT_TIME), 2, '0');
    current_tenant_id VARCHAR;
    warehouse_cursor CURSOR FOR
        SELECT c.WAREHOUSE_NAME, c.WAREHOUSE_ID, s.TARGET_SIZE, c.STATUS
        FROM UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_WAREHOUSE_CONFIG c
        INNER JOIN UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_STATIC_SCHEDULE s
            ON c.WAREHOUSE_ID = s.WAREHOUSE_ID
        WHERE c.TENANT_ID = current_tenant_id
            AND s.DAY_OF_WEEK = current_day_of_week
            AND s.HOUR_OF_DAY = current_hour_of_day
            AND s.STRATEGY = 'STATIC';
BEGIN
    -- Get current tenant ID from session context or configuration
    SET current_tenant_id = CURRENT_ACCOUNT();
    
    -- Log the procedure execution start
    INSERT INTO UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_EXECUTION_LOG
        (WAREHOUSE_ID, WAREHOUSE_NAME, ACTION, STATUS, EXECUTION_TIME, TENANT_ID)
    VALUES
        (NULL, 'SP_EXECUTE_STATIC_RIGHTSIZING', 'PROCEDURE_START', 'STARTED', CURRENT_TIMESTAMP, current_tenant_id);

    -- Process ACTIVE warehouses
    FOR warehouse_record IN 
        SELECT c.WAREHOUSE_NAME, c.WAREHOUSE_ID, s.TARGET_SIZE
        FROM UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_WAREHOUSE_CONFIG c
        INNER JOIN UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_STATIC_SCHEDULE s
            ON c.WAREHOUSE_ID = s.WAREHOUSE_ID
        WHERE c.TENANT_ID = current_tenant_id
            AND s.DAY_OF_WEEK = current_day_of_week
            AND s.HOUR_OF_DAY = current_hour_of_day
            AND s.STRATEGY = 'STATIC'
            AND c.STATUS = 'ACTIVE'
    DO
        BEGIN
            -- Execute the ALTER WAREHOUSE command
            EXECUTE IMMEDIATE 'ALTER WAREHOUSE ' || warehouse_record.WAREHOUSE_NAME || ' SET WAREHOUSE_SIZE = ' || warehouse_record.TARGET_SIZE;
            
            -- Log the execution
            INSERT INTO UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_EXECUTION_LOG
                (WAREHOUSE_ID, WAREHOUSE_NAME, ACTION, TARGET_SIZE, STATUS, EXECUTION_TIME, TENANT_ID)
            VALUES
                (warehouse_record.WAREHOUSE_ID, warehouse_record.WAREHOUSE_NAME, 'RESIZE', warehouse_record.TARGET_SIZE, 'SUCCESS', CURRENT_TIMESTAMP, current_tenant_id);
        EXCEPTION WHEN OTHERS THEN
            INSERT INTO UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_EXECUTION_LOG
                (WAREHOUSE_ID, WAREHOUSE_NAME, ACTION, TARGET_SIZE, STATUS, EXECUTION_TIME, ERROR_MESSAGE, TENANT_ID)
            VALUES
                (warehouse_record.WAREHOUSE_ID, warehouse_record.WAREHOUSE_NAME, 'RESIZE', warehouse_record.TARGET_SIZE, 'FAILED', CURRENT_TIMESTAMP, SQLERRM, current_tenant_id);
        END;
    END FOR;

    -- Process SUSPENDED warehouses
    FOR warehouse_record IN 
        SELECT c.WAREHOUSE_NAME, c.WAREHOUSE_ID, s.TARGET_SIZE
        FROM UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_WAREHOUSE_CONFIG c
        INNER JOIN UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_STATIC_SCHEDULE s
            ON c.WAREHOUSE_ID = s.WAREHOUSE_ID
        WHERE c.TENANT_ID = current_tenant_id
            AND s.DAY_OF_WEEK = current_day_of_week
            AND s.HOUR_OF_DAY = current_hour_of_day
            AND s.STRATEGY = 'STATIC'
            AND c.STATUS = 'SUSPENDED'
    DO
        BEGIN
            -- Execute the ALTER WAREHOUSE command for suspended warehouses
            EXECUTE IMMEDIATE 'ALTER WAREHOUSE ' || warehouse_record.WAREHOUSE_NAME || ' SET WAREHOUSE_SIZE = ' || warehouse_record.TARGET_SIZE;
            
            -- Log the execution
            INSERT INTO UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_EXECUTION_LOG
                (WAREHOUSE_ID, WAREHOUSE_NAME, ACTION, TARGET_SIZE, STATUS, EXECUTION_TIME, TENANT_ID)
            VALUES
                (warehouse_record.WAREHOUSE_ID, warehouse_record.WAREHOUSE_NAME, 'RESIZE', warehouse_record.TARGET_SIZE, 'SUCCESS', CURRENT_TIMESTAMP, current_tenant_id);
        EXCEPTION WHEN OTHERS THEN
            INSERT INTO UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_EXECUTION_LOG
                (WAREHOUSE_ID, WAREHOUSE_NAME, ACTION, TARGET_SIZE, STATUS, EXECUTION_TIME, ERROR_MESSAGE, TENANT_ID)
            VALUES
                (warehouse_record.WAREHOUSE_ID, warehouse_record.WAREHOUSE_NAME, 'RESIZE', warehouse_record.TARGET_SIZE, 'FAILED', CURRENT_TIMESTAMP, SQLERRM, current_tenant_id);
        END;
    END FOR;

    -- Log the procedure execution completion
    INSERT INTO UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_EXECUTION_LOG
        (WAREHOUSE_ID, WAREHOUSE_NAME, ACTION, STATUS, EXECUTION_TIME, TENANT_ID)
    VALUES
        (NULL, 'SP_EXECUTE_STATIC_RIGHTSIZING', 'PROCEDURE_COMPLETED', 'COMPLETED', CURRENT_TIMESTAMP, current_tenant_id);
END;
$$;

-- Create or replace a procedure to share T_UNRAVEL_EXECUTION_LOG table
CREATE OR REPLACE PROCEDURE SP_SHARE_EXECUTION_LOG(ACCOUNT_ID VARCHAR)
RETURNS STRING NOT NULL
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    use_statement VARCHAR;
    res RESULTSET;
BEGIN
    -- Create share if it doesn't exist
    CREATE SHARE IF NOT EXISTS S_UNRAVEL_EXECUTION_LOG_SHARE;
    
    -- Grant usage on database and schema to the share
    GRANT USAGE ON DATABASE UNRAVEL_REVERSE_SHARE_DB TO SHARE S_UNRAVEL_EXECUTION_LOG_SHARE;
    GRANT USAGE ON SCHEMA UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA TO SHARE S_UNRAVEL_EXECUTION_LOG_SHARE;
    
    -- Grant select on T_UNRAVEL_EXECUTION_LOG table to the share
    GRANT SELECT ON TABLE UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA.T_UNRAVEL_EXECUTION_LOG TO SHARE S_UNRAVEL_EXECUTION_LOG_SHARE;
    
    -- Add account to the share
    use_statement := 'ALTER SHARE S_UNRAVEL_EXECUTION_LOG_SHARE ADD ACCOUNTS = ' || ACCOUNT_ID::VARIANT::VARCHAR;
    res := (EXECUTE IMMEDIATE :use_statement);
    
    RETURN 'SUCCESS';
END;
$$;

-- Call the procedure to share T_UNRAVEL_EXECUTION_LOG table with the target account
CALL SP_SHARE_EXECUTION_LOG('<TARGET_ACCOUNT_ID>');

-- Create or replace a scheduled task to execute static rightsizing
CREATE OR REPLACE TASK SP_EXECUTE_STATIC_RIGHTSIZING_TASK
 WAREHOUSE = UNRAVELDATA
 SCHEDULE = '60 MINUTE'
AS
CALL SP_EXECUTE_STATIC_RIGHTSIZING('UNRAVEL_REVERSE_SHARE_DB','UNRAVEL_RIGHTSIZING_SCHEMA');

-- Resume the task to enable it
ALTER TASK SP_EXECUTE_STATIC_RIGHTSIZING_TASK RESUME;

