-- Create Database and Schema
-- Database format: <CUSTOMER_NAME>_REVERSE_SHARE
-- Schema format: <ACCOUNT_NAME>_UNRAVEL_SHARE
CREATE DATABASE IF NOT EXISTS <CUSTOMER_NAME>_REVERSE_SHARE;
CREATE SCHEMA IF NOT EXISTS <ACCOUNT_NAME>_UNRAVEL_SHARE;

-- Set the database and schema context
-- Database format: <CUSTOMER_NAME>_REVERSE_SHARE
-- Schema format: <ACCOUNT_NAME>_UNRAVEL_SHARE
USE DATABASE <CUSTOMER_NAME>_REVERSE_SHARE;
USE SCHEMA <ACCOUNT_NAME>_UNRAVEL_SHARE;

-- Procedure to create all required tables
CREATE OR REPLACE PROCEDURE CREATE_UNRAVEL_TABLES()
RETURNS STRING NOT NULL
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    CREATE TABLE IF NOT EXISTS T_UNRAVEL_WAREHOUSE_CONFIG (
        TENANT_ID STRING,
        ACCT_ID STRING,
        WAREHOUSE_NAME STRING,
        WAREHOUSE_ID NUMBER,
        STATUS STRING,
        STRATEGY STRING,
        PERFORMANCE_PROFILE STRING,
        AUTO_UPDATE_CYCLE_DAYS STRING,
        LAST_AUTO_UPDATE_DATE TIMESTAMP,
        MIN_SIZE STRING,
        MAX_SIZE STRING,
        CURRENT_SIZE STRING,
        CLUSTER_SIZE NUMBER,
        AUTO_SUSPEND_SEC NUMBER,
        AUTO_RESUME BOOLEAN,
        STATEMENT_TIMEOUT_SEC NUMBER,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    );

    CREATE TABLE IF NOT EXISTS T_UNRAVEL_STATIC_SCHEDULE (
        TENANT_ID STRING,
        ACCT_ID STRING,
        WAREHOUSE_NAME STRING,
        WAREHOUSE_ID NUMBER,
        DAY_OF_WEEK NUMBER,
        HOUR_OF_DAY NUMBER,
        TARGET_SIZE STRING,
        EXPECTED_QUEUE FLOAT,
        EXPECTED_SPILL FLOAT,
        EXPECTED_CREDITS FLOAT,
        CONFIDENCE FLOAT,
        GENERATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';
END;
$$;

-- Procedure to share tables with customer account via secure share
CREATE OR REPLACE PROCEDURE SHARE_UNRAVEL_TABLES_TO_CUSTOMER(ACCOUNTID VARCHAR)
RETURNS STRING NOT NULL
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    use_statement VARCHAR;
    res RESULTSET;
BEGIN
    CREATE SHARE IF NOT EXISTS UNRAVEL_SECURE_SHARE;

    GRANT USAGE ON DATABASE <CUSTOMER_NAME>_REVERSE_SHARE TO SHARE UNRAVEL_SECURE_SHARE;
    GRANT USAGE ON SCHEMA <CUSTOMER_NAME>_REVERSE_SHARE.<ACCOUNT_NAME>_UNRAVEL_SHARE TO SHARE UNRAVEL_SECURE_SHARE;

    GRANT SELECT ON TABLE T_UNRAVEL_WAREHOUSE_CONFIG TO SHARE UNRAVEL_SECURE_SHARE;
    GRANT SELECT ON TABLE T_UNRAVEL_STATIC_SCHEDULE TO SHARE UNRAVEL_SECURE_SHARE;

    use_statement := 'ALTER SHARE UNRAVEL_SECURE_SHARE ADD ACCOUNTS = ' || ACCOUNTID::VARIANT::VARCHAR;
    res := (EXECUTE IMMEDIATE :use_statement);

    RETURN 'SUCCESS';
END;
$$;

-- Step-1: Call procedure to create all tables
CALL CREATE_UNRAVEL_TABLES();

-- Step-2: Call procedure to share tables with customer account
CALL SHARE_UNRAVEL_TABLES_TO_CUSTOMER('<Customer Account Identifier>');
