-- Create Database and Schema
CREATE DATABASE IF NOT EXISTS UNRAVEL_REVERSE_SHARE_DB;
CREATE SCHEMA IF NOT EXISTS UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA;

-- Set the database and schema context
USE UNRAVEL_REVERSE_SHARE_DB;
USE UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA;

-- Procedure to create all required tables
CREATE OR REPLACE PROCEDURE CREATE_UNRAVEL_TABLES()
RETURNS STRING NOT NULL
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    CREATE TABLE IF NOT EXISTS T_UNRAVEL_WAREHOUSE_CONFIG (
        TENANT_ID STRING,
        ACCT_ID STRING,
        WAREHOUSE_NAME STRING,
        STATUS STRING,
        STRATEGY STRING,
        PERFORMANCE_PROFILE STRING,
        AUTO_UPDATE_CYCLE_DAYS STRING,
        LAST_AUTO_UPDATE_DATE TIMESTAMP,
        MIN_SIZE STRING,
        MAX_SIZE STRING,
        CURRENT_SIZE STRING,
        CLUSTER_SIZE NUMBER,
        AUTO_SUSPEND_SEC NUMBER,
        AUTO_RESUME BOOLEAN,
        STATEMENT_TIMEOUT_SEC NUMBER,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    );

    CREATE TABLE IF NOT EXISTS T_UNRAVEL_STATIC_SCHEDULE (
        TENANT_ID STRING,
        ACCT_ID STRING,
        WAREHOUSE_NAME STRING,
        DAY_OF_WEEK NUMBER,
        HOUR_OF_DAY NUMBER,
        TARGET_SIZE STRING,
        EXPECTED_QUEUE FLOAT,
        EXPECTED_SPILL FLOAT,
        EXPECTED_CREDITS FLOAT,
        CONFIDENCE FLOAT,
        GENERATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    );

    CREATE TABLE IF NOT EXISTS T_UNRAVEL_EXECUTION_LOG (
        TENANT_ID STRING,
        ACCT_ID STRING,
        EXECUTION_ID STRING,
        EXECUTION_TIME TIMESTAMP,
        WAREHOUSE_NAME STRING,
        STRATEGY STRING,
        CURRENT_SIZE STRING,
        NEW_SIZE STRING,
        CURRENT_CLUSTER NUMBER,
        NEW_CLUSTER NUMBER,
        CURRENT_TIMEOUT NUMBER,
        NEW_TIMEOUT NUMBER,
        ACTION STRING,
        RESULT STRING,
        ERROR_MESSAGE STRING
    );

    RETURN 'SUCCESS';
END;

-- Procedure to share tables with customer account via secure share
CREATE OR REPLACE PROCEDURE SHARE_UNRAVEL_TABLES_TO_CUSTOMER(ACCOUNTID VARCHAR)
RETURNS STRING NOT NULL
LANGUAGE SQL
EXECUTE AS CALLER
AS
DECLARE
    use_statement VARCHAR;
    res RESULTSET;
BEGIN
    CREATE SHARE IF NOT EXISTS UNRAVEL_SECURE_SHARE;

    GRANT USAGE ON DATABASE UNRAVEL_REVERSE_SHARE_DB TO SHARE UNRAVEL_SECURE_SHARE;
    GRANT USAGE ON SCHEMA UNRAVEL_REVERSE_SHARE_DB.UNRAVEL_RIGHTSIZING_SCHEMA TO SHARE UNRAVEL_SECURE_SHARE;

    GRANT SELECT ON TABLE T_UNRAVEL_WAREHOUSE_CONFIG TO SHARE UNRAVEL_SECURE_SHARE;
    GRANT SELECT ON TABLE T_UNRAVEL_STATIC_SCHEDULE TO SHARE UNRAVEL_SECURE_SHARE;
    GRANT SELECT ON TABLE T_UNRAVEL_EXECUTION_LOG TO SHARE UNRAVEL_SECURE_SHARE;

    use_statement := 'ALTER SHARE UNRAVEL_SECURE_SHARE ADD ACCOUNTS = ' || ACCOUNTID::VARIANT::VARCHAR;
    res := (EXECUTE IMMEDIATE :use_statement);
    
    RETURN 'SUCCESS';
END;

-- Step-0: Call procedure to create all tables
CALL CREATE_UNRAVEL_TABLES();

-- Step-1: Call procedure to share tables with customer account
CALL SHARE_UNRAVEL_TABLES_TO_CUSTOMER('<Customer Account Identifier>');
